/**
 * CARE - ZeroStateOnboardingCard Component
 * Onboarding Hero Card ("Get Started with CARE"):
 * - Header: "Welcome to your Cognitive Retention Hub" (Newsreader serif)
 * - Subtitle: Explaining AI cognitive atrophy, Ebbinghaus decay, and active recall drills
 * - 3-Step Horizontal Setup Cards (Step 01, Step 02, Step 03 with tags)
 * - Tip Bar: Amber prompt guiding user to create first entry manually
 * - Security Microcopy: Zero telemetry leakage · Local-first IPC socket · Cryptographically sandboxed per UID
 */

import React from 'react';
import {
  Sparkles,
  FileCode2,
  Cpu,
  MessageSquareCode,
  Lightbulb,
  ShieldCheck,
  CheckCircle2,
  ArrowRight,
} from 'lucide-react';

interface ZeroStateOnboardingCardProps {
  onLogClick: () => void;
}

export const ZeroStateOnboardingCard: React.FC<ZeroStateOnboardingCardProps> = ({ onLogClick }) => {
  const steps = [
    {
      step: '01',
      title: 'Log Technical Notes',
      description:
        'Capture code snippets, system designs, and whether the code was generated by prompt, spec, or manual derivation.',
      tags: ['Markdown & Web', 'Direct Capture'],
      icon: FileCode2,
      accentColor: 'text-[#006948] bg-[#ECFDF5] border-emerald-200',
    },
    {
      step: '02',
      title: 'AI Synthesis & Decay Model',
      description:
        'Gemini vectorizes canonical mental models and computes memory decay trajectories via Priority(t) calculus.',
      tags: ['Priority(t) Calculus', 'Gemini 2.5'],
      icon: Cpu,
      accentColor: 'text-[#1E293B] bg-[#F0F3FF] border-[#CCD8FF]',
    },
    {
      step: '03',
      title: 'Peer Active Recall',
      description:
        'Engage in 2-minute Socratic dialogue right as retention approaches the critical threshold, restoring neural durability.',
      tags: ['Socratic Dialogue', '2m Interleaved'],
      icon: MessageSquareCode,
      accentColor: 'text-[#8D4B00] bg-[#FFF8ED] border-amber-200',
    },
  ];

  return (
    <div className="bg-white rounded-2xl border border-[#E5E0D8] p-6 sm:p-7 shadow-xs relative overflow-hidden text-left">
      {/* Background subtle scholastic texture/gradient */}
      <div className="absolute top-0 right-0 w-80 h-80 bg-gradient-to-bl from-[#F0F3FF]/70 via-[#FAF8F5]/30 to-transparent pointer-events-none -z-0 rounded-bl-full" />

      <div className="relative z-10 space-y-6">
        {/* Header and Subtitle */}
        <div className="space-y-2 max-w-3xl">
          <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full bg-[#ECFDF5] border border-emerald-200 text-[#006948] text-[11px] font-mono font-semibold uppercase tracking-wider">
            <Sparkles className="w-3.5 h-3.5 text-[#006948]" />
            <span>Onboarding • Continuous Cognitive Mastery</span>
          </div>

          <h2 className="font-serif text-2xl sm:text-3xl lg:text-[32px] font-bold text-[#1E293B] tracking-tight leading-snug">
            Welcome to your Cognitive Retention Hub
          </h2>

          <p className="text-sm text-[#505F76] leading-relaxed">
            When language models write 70% of production code, engineering intuition atrophies silently. CARE measures AI reliance, tracks memory half-life through mathematical Ebbinghaus trajectories, and delivers 2-minute Socratic recall drills right before critical mental models fade.
          </p>
        </div>

        {/* 3-Step Horizontal Setup Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-1">
          {steps.map((item) => {
            const Icon = item.icon;
            return (
              <div
                key={item.step}
                className="bg-[#FAF8F5]/80 hover:bg-white rounded-xl border border-[#E5E0D8] p-4 flex flex-col justify-between space-y-3 transition-all hover:shadow-xs group hover:border-[#D5CFC6]"
              >
                <div className="space-y-2.5">
                  {/* Step number and icon badge */}
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-xs font-bold text-[#505F76] group-hover:text-[#006948] transition-colors">
                      Step {item.step}
                    </span>
                    <div
                      className={`w-7 h-7 rounded-lg border flex items-center justify-center ${item.accentColor} shadow-2xs`}
                    >
                      <Icon className="w-3.5 h-3.5" />
                    </div>
                  </div>

                  {/* Title */}
                  <h3 className="font-serif font-bold text-base text-[#1E293B] leading-tight">
                    {item.title}
                  </h3>

                  {/* Description */}
                  <p className="text-xs text-[#505F76] leading-relaxed font-sans">
                    {item.description}
                  </p>
                </div>

                {/* Tags */}
                <div className="pt-2 border-t border-[#EAE6DF] flex flex-wrap gap-1.5">
                  {item.tags.map((tag) => (
                    <span
                      key={tag}
                      className="px-2 py-0.5 rounded bg-white border border-[#E5E0D8] text-[10px] font-mono text-[#505F76] font-medium"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            );
          })}
        </div>

        {/* Tip Bar */}
        <div className="bg-[#FFF8ED] border border-amber-200/90 rounded-xl p-3 sm:p-3.5 flex items-center justify-between gap-3 text-xs text-[#8D4B00]">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-amber-100 flex items-center justify-center shrink-0 text-amber-800">
              <Lightbulb className="w-4 h-4 text-amber-700" />
            </div>
            <span className="font-medium leading-relaxed">
              <strong>Pro-tip:</strong> Create your first entry manually below or link the CLI telemetry socket to seed your baseline knowledge graph.
            </span>
          </div>

          <button
            type="button"
            onClick={onLogClick}
            className="shrink-0 px-3 py-1.5 rounded-lg bg-[#8D4B00] hover:bg-[#723C00] text-white font-medium text-xs transition-colors flex items-center gap-1 shadow-2xs cursor-pointer"
          >
            <span>Log Note Now</span>
            <ArrowRight className="w-3 h-3" />
          </button>
        </div>

        {/* Security Microcopy */}
        <div className="pt-2 flex flex-wrap items-center justify-between gap-2 text-[11px] font-mono text-[#505F76] border-t border-[#F0ECE6]">
          <div className="flex items-center gap-1.5">
            <ShieldCheck className="w-3.5 h-3.5 text-[#006948]" />
            <span>Zero telemetry leakage · Local-first IPC socket · Cryptographically sandboxed per UID</span>
          </div>
          <span className="text-[#006948] font-semibold">Engine Status: Online v0.1</span>
        </div>
      </div>
    </div>
  );
};
