/**
/**
 * CARE - ScorecardDisplay Component (Slice 4)
 * Renders the structured evaluation scorecard generated by gemini-3.8-flash:
 *  - Depth score (0-100) & score tier badges
 *  - Conceptual depth & practical application ratings (1-5)
 *  - Identified conceptual gaps
 *  - Actionable retention recommendations
 *  - Updated decay priority score and H(t) recall deficit shifts
 */

import React from 'react';
import {
  Award,
  CheckCircle2,
  AlertTriangle,
  Lightbulb,
  TrendingDown,
  Brain,
  RotateCcw,
  Sparkles,
  ArrowRight,
  ShieldCheck,
  Target,
  BarChart2,
} from 'lucide-react';
import { RecallSession, RecallEvaluation, TopicRetentionState } from '../../types';

interface ScorecardDisplayProps {
  session: RecallSession;
  evaluation: RecallEvaluation;
  updatedTopic?: TopicRetentionState | null;
  onDone: () => void;
  onRestartSession?: () => void;
}

export const ScorecardDisplay: React.FC<ScorecardDisplayProps> = ({
  session,
  evaluation,
  updatedTopic,
  onDone,
  onRestartSession,
}) => {
  const scorePct = evaluation.scorePercentage ?? Math.round(((evaluation.overallScore - 1.0) / 4.0) * 100);

  // Calibrate score tier styling
  let tierLabel = 'Needs Reinforcement';
  let tierBadgeStyle = 'bg-rose-950/60 text-rose-300 border-rose-800';
  let scoreColor = 'text-rose-400';
  let ringColor = 'border-rose-500';

  if (scorePct >= 85) {
    tierLabel = 'Exceptional Mastery';
    tierBadgeStyle = 'bg-emerald-950/60 text-emerald-300 border-emerald-800';
    scoreColor = 'text-emerald-400';
    ringColor = 'border-emerald-500';
  } else if (scorePct >= 70) {
    tierLabel = 'Solid Proficiency';
    tierBadgeStyle = 'bg-teal-950/60 text-teal-300 border-teal-800';
    scoreColor = 'text-teal-400';
    ringColor = 'border-teal-500';
  } else if (scorePct >= 55) {
    tierLabel = 'Emerging Concept';
    tierBadgeStyle = 'bg-amber-950/60 text-amber-300 border-amber-800';
    scoreColor = 'text-amber-400';
    ringColor = 'border-amber-500';
  }

  // Calculate decay priority comparison if updated topic is provided
  const initialPriority = session.initialBreakdown?.priorityScore ?? 50.0;
  const currentPriority = updatedTopic?.currentPriorityScore ?? Math.max(10, Math.round(initialPriority * 0.45));
  const priorityDrop = Math.round((initialPriority - currentPriority) * 10) / 10;

  return (
    <div id="recall-scorecard-container" className="space-y-6 text-stone-100">
      {/* Top Banner with Score Gauge */}
      <div className="bg-stone-925 border border-stone-800 rounded-2xl p-6 sm:p-7 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/5 rounded-full blur-3xl pointer-events-none" />

        <div className="flex flex-col sm:flex-row items-center justify-between gap-6 relative z-10">
          <div className="space-y-2 text-center sm:text-left">
            <div className="flex items-center justify-center sm:justify-start gap-2 flex-wrap">
              <span className="text-[11px] font-mono uppercase tracking-wider px-2.5 py-0.5 rounded bg-stone-800 text-stone-300 border border-stone-700">
                Evaluation Scorecard
              </span>
              <span className={`text-[11px] font-mono px-2.5 py-0.5 rounded border ${tierBadgeStyle}`}>
                {tierLabel}
              </span>
            </div>

            <h2 className="text-xl sm:text-2xl font-bold text-stone-100">
              {session.topicName}
            </h2>

            <p className="text-xs sm:text-sm text-stone-400 max-w-lg">
              Socratic interview completed across {session.turns.length} conversational turns at{' '}
              <span className="text-emerald-400 capitalize font-medium">{session.targetDepth || 'intermediate'}</span>{' '}
              rigor.
            </p>
          </div>

          {/* Radial / Donut Score Card */}
          <div className="flex items-center gap-4 shrink-0 bg-stone-950/90 border border-stone-800 p-4 rounded-2xl shadow-lg">
            <div className={`w-20 h-20 rounded-full border-4 ${ringColor} flex flex-col items-center justify-center bg-stone-900 shadow-inner`}>
              <span className={`text-2xl font-extrabold ${scoreColor} leading-none`}>
                {scorePct}
              </span>
              <span className="text-[10px] text-stone-500 uppercase font-mono mt-0.5">/ 100</span>
            </div>

            <div className="space-y-1.5 text-xs font-mono">
              <div className="text-stone-400 flex items-center justify-between gap-4">
                <span>Concept Depth:</span>
                <span className="text-stone-200 font-semibold">{evaluation.conceptualDepth} / 5</span>
              </div>
              <div className="text-stone-400 flex items-center justify-between gap-4">
                <span>Application:</span>
                <span className="text-stone-200 font-semibold">{evaluation.practicalApplication} / 5</span>
              </div>
              <div className="text-stone-400 flex items-center justify-between gap-4">
                <span>Overall Grade:</span>
                <span className="text-emerald-400 font-bold">{evaluation.overallScore.toFixed(1)} / 5.0</span>
              </div>
            </div>
          </div>
        </div>

        {/* Priority Decay Impact telemetry */}
        <div className="mt-6 pt-5 border-t border-stone-800/80 grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs font-mono">
          <div className="p-3 bg-stone-950/70 rounded-xl border border-stone-800 flex items-center justify-between">
            <span className="text-stone-400">Pre-Session Priority:</span>
            <span className="text-rose-400 font-bold">{initialPriority.toFixed(1)}</span>
          </div>

          <div className="p-3 bg-stone-950/70 rounded-xl border border-stone-800 flex items-center justify-between">
            <span className="text-stone-400">Consolidated Priority:</span>
            <span className="text-emerald-400 font-bold">{currentPriority.toFixed(1)}</span>
          </div>

          <div className="p-3 bg-emerald-950/30 rounded-xl border border-emerald-900/60 flex items-center justify-between">
            <span className="text-emerald-300 flex items-center gap-1.5">
              <TrendingDown className="w-3.5 h-3.5 text-emerald-400" />
              Decay Mitigated:
            </span>
            <span className="text-emerald-300 font-bold">
              {priorityDrop > 0 ? `-${priorityDrop.toFixed(1)} pts` : 'Consolidated'}
            </span>
          </div>
        </div>
      </div>

      {/* Key Takeaway Banner */}
      {evaluation.keyTakeaway && (
        <div className="p-4 bg-emerald-950/20 border border-emerald-900/40 rounded-xl flex items-start gap-3">
          <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400 shrink-0 mt-0.5">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <div className="text-xs font-semibold uppercase tracking-wider text-emerald-400 font-mono">
              Core Architectural Mental Model
            </div>
            <p className="text-xs sm:text-sm text-stone-200 mt-1 leading-relaxed">
              "{evaluation.keyTakeaway}"
            </p>
          </div>
        </div>
      )}

      {/* Gaps & Retention Recommendations Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Identified Conceptual Gaps */}
        <div className="bg-stone-925 border border-stone-800 rounded-xl p-5 space-y-3">
          <div className="flex items-center gap-2 text-amber-400 text-xs sm:text-sm font-semibold">
            <AlertTriangle className="w-4 h-4 text-amber-400" />
            <span>Identified Conceptual Gaps &amp; Nuances</span>
          </div>

          {evaluation.identifiedGaps && evaluation.identifiedGaps.length > 0 ? (
            <ul className="space-y-2 text-xs text-stone-300">
              {evaluation.identifiedGaps.map((gap, idx) => (
                <li key={idx} className="flex items-start gap-2.5 p-2.5 bg-stone-950/60 rounded-lg border border-stone-800/80 leading-relaxed">
                  <span className="w-1.5 h-1.5 rounded-full bg-amber-400 shrink-0 mt-1.5" />
                  <span>{gap}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-xs text-stone-400 italic">No major conceptual gaps identified during this interview.</p>
          )}

          {evaluation.areasForImprovement && (
            <div className="pt-2 text-[11px] text-stone-400 leading-normal border-t border-stone-800/60">
              <span className="font-semibold text-stone-300">Focus Insight:</span> {evaluation.areasForImprovement}
            </div>
          )}
        </div>

        {/* Actionable Retention Tips */}
        <div className="bg-stone-925 border border-stone-800 rounded-xl p-5 space-y-3">
          <div className="flex items-center gap-2 text-emerald-400 text-xs sm:text-sm font-semibold">
            <Lightbulb className="w-4 h-4 text-emerald-400" />
            <span>Actionable Retention Recommendations</span>
          </div>

          {evaluation.retentionTips && evaluation.retentionTips.length > 0 ? (
            <ul className="space-y-2 text-xs text-stone-300">
              {evaluation.retentionTips.map((tip, idx) => (
                <li key={idx} className="flex items-start gap-2.5 p-2.5 bg-stone-950/60 rounded-lg border border-stone-800/80 leading-relaxed">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                  <span>{tip}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-xs text-stone-400 italic">Review notes in 5-7 days to prevent future knowledge decay.</p>
          )}

          {evaluation.strengths && (
            <div className="pt-2 text-[11px] text-stone-400 leading-normal border-t border-stone-800/60">
              <span className="font-semibold text-stone-300">Demonstrated Strengths:</span> {evaluation.strengths}
            </div>
          )}
        </div>
      </div>

      {/* Security & Firestore Persistence Confirmation */}
      <div className="p-3 bg-stone-950 border border-stone-800 rounded-xl flex items-center justify-between text-[11px] text-stone-400 font-mono">
        <div className="flex items-center gap-2">
          <ShieldCheck className="w-4 h-4 text-emerald-400" />
          <span>Scorecard &amp; updated H(t) state persisted to Firestore under your user ID.</span>
        </div>
        <span className="text-stone-500">Session ID: {session.sessionId}</span>
      </div>

      {/* Action Footer */}
      <div className="pt-2 flex items-center justify-between gap-3">
        {onRestartSession && (
          <button
            id="btn-restart-recall-session"
            type="button"
            onClick={onRestartSession}
            className="px-4 py-2.5 bg-stone-800 hover:bg-stone-750 text-stone-200 text-xs sm:text-sm font-medium rounded-xl transition-colors flex items-center gap-2"
          >
            <RotateCcw className="w-3.5 h-3.5 text-stone-400" />
            <span>Retake Socratic Interview</span>
          </button>
        )}

        <div className="flex items-center gap-3 ml-auto">
          <button
            id="btn-scorecard-done"
            type="button"
            onClick={onDone}
            className="px-6 py-2.5 bg-emerald-500 hover:bg-emerald-400 text-stone-950 font-semibold text-xs sm:text-sm rounded-xl transition-colors flex items-center gap-2 shadow-sm"
          >
            <span>Return to Recall Dashboard</span>
            <ArrowRight className="w-4 h-4 text-stone-950" />
          </button>
        </div>
      </div>
    </div>
  );
};
